LANG=$1
SPLIT=lemma
PORTION=0.75

# morphodetection
# python run_transducer.py --dynet-seed 0 --dynet-mem 1000 --dynet-autobatch ON --transducer=haem --sigm2017format --input=100 --feat-input=20 --action-input=100 --enc-hidden=200 --dec-hidden=200 --enc-layers=1 --dec-layers=1 --mlp=0 --nonlin=ReLU --dropout=0.5 --optimization=ADADELTA --l2=0 --batch-size=1 --decbatch-size=1 --patience=10 --epochs=50 --align-cls --tag-wraps=both --iterations=150 --param-tying --mode=mle --beam-width=0 --beam-widths=4 --pretrain-epochs=0 --sample-size=20 --scale-negative=1 ../../morphodetection/initial_version/outputs/9_${LANG}V_5sup_overfit/inflec_data_0.txt dummy ../my_results/${LANG} --test-path=../../pcfp-data/data/${LANG}.um.V.txt --reload-path=dummy --hall-path=../../inflection/md/${LANG}-hall
# python run_transducer.py --dynet-seed 0 --dynet-mem 1000 --dynet-autobatch ON --transducer=haem --sigm2017format --input=100 --feat-input=20 --action-input=100 --enc-hidden=200 --dec-hidden=200 --enc-layers=1 --dec-layers=1 --mlp=0 --nonlin=ReLU --dropout=0.5 --optimization=ADADELTA --l2=0 --batch-size=1 --decbatch-size=1 --patience=10 --epochs=50 --align-cls --tag-wraps=both --iterations=150 --param-tying --mode=mle --beam-width=0 --beam-widths=4 --pretrain-epochs=0 --sample-size=20 --scale-negative=1 ../../morphodetection/initial_version/outputs/20201114-015107_trV_5sup_enh1/inflec_data_0.txt dummy ../my_results/${LANG} --test-path=../../pcfp-data/data/${LANG}.um.V.txt --reload-path=dummy
# python run_transducer.py --dynet-seed 0 --dynet-mem 1000 --dynet-autobatch ON --transducer=haem --sigm2017format --input=100 --feat-input=20 --action-input=100 --enc-hidden=200 --dec-hidden=200 --enc-layers=1 --dec-layers=1 --mlp=0 --nonlin=ReLU --dropout=0.5 --optimization=ADADELTA --l2=0 --batch-size=1 --decbatch-size=1 --patience=10 --epochs=50 --align-cls --tag-wraps=both --iterations=150 --param-tying --mode=mle --beam-width=0 --beam-widths=4 --pretrain-epochs=0 --sample-size=20 --scale-negative=1 ../../morphodetection/initial_version/datasets/data_${LANG}V_all-ns_5sup_enhance_2_max.txt dummy ../my_results/${LANG}_comb --test-path=../../pcfp-data/data/${LANG}.um.V.txt --reload-path=dummy

# clause morphology
python run_transducer.py --dynet-seed 100 --dynet-mem 1000 --dynet-autobatch ON --transducer=haem --input=100 --feat-input=20 --action-input=100 --enc-hidden=200 --dec-hidden=200 --enc-layers=1 --dec-layers=1 --mlp=0 --nonlin=ReLU --dropout=0.5 --optimization=ADADELTA --l2=0 --batch-size=1 --decbatch-size=1 --patience=10 --epochs=50 --align-cls --tag-wraps=both --iterations=150 --param-tying --mode=mle --beam-width=0 --beam-widths=4 --pretrain-epochs=0 --sample-size=20 --scale-negative=1 ../../clause_morphology/datasets/${SPLIT}/reinf/${LANG}_${PORTION}_train dummy ../my_results/clause/${SPLIT}/${LANG}_${PORTION} --test-path=../../clause_morphology/datasets/${SPLIT}/reinf/${LANG}_test --reload-path=dummy